/**
 * Fake userId aligned with API MOCK_USER_ID (used while auth is not implemented).
 * Same UUID as apps/api src/app/config/mock-user.ts
 */
export const MOCK_USER_ID = "aaaaaaaa-bbbb-4ccc-d000-000000000000" as const;

export const PROJECTS_MOCKS = [
	{
		id: "1",
		name: "Casa",
		emoji: "🏠",
		userId: MOCK_USER_ID,
		todos: [
			{
				id: "1",
				title: "Ração do bob",
				description: "10 semanas",
				dueDate: "2025-11-30",
				completed: false,
				tags: ["Casa 🏠", "Compras"],
				projectId: "1",
				userId: MOCK_USER_ID,
			},
			{
				id: "2",
				title: "Sabão pastoso",
				description: "6 semanas",
				dueDate: "2025-01-04",
				completed: false,
				tags: ["Casa 🏠", "Compras"],
				projectId: "1",
				userId: MOCK_USER_ID,
			},
		],
	},
	{
		id: "2",
		name: "Estudos",
		emoji: "🎓",
		userId: MOCK_USER_ID,
		todos: [
			{
				id: "3",
				title: "Practice speak in english",
				description: "Gliglish · learn languages by...",
				dueDate: "2024-12-20",
				completed: false,
				tags: ["Estudos 🎓", "Inglês"],
				projectId: "2",
				userId: MOCK_USER_ID,
			},
			{
				id: "4",
				title: "Ler texto em ingles",
				description: "30 minutos",
				dueDate: "2025-04-15",
				completed: false,
				tags: ["Estudos 🎓", "Inglês"],
				projectId: "2",
				userId: MOCK_USER_ID,
			},
			{
				id: "5",
				title: "Assistir um video em ingles",
				description: "15 minutos https://www.youtu...",
				dueDate: "2025-05-15",
				completed: false,
				tags: ["Estudos 🎓", "Inglês"],
				projectId: "2",
				userId: MOCK_USER_ID,
			},
			{
				id: "6",
				title: "Procurar evento no meetup",
				dueDate: "2025-11-28",
				completed: false,
				tags: ["Estudos 🎓"],
				projectId: "2",
				userId: MOCK_USER_ID,
			},
		],
	},
	{
		id: "3",
		name: "Pessoal",
		emoji: "😊",
		userId: MOCK_USER_ID,
		todos: [
			{
				id: "7",
				title: "Assistir vídeo do Cesar",
				description: "https://www.youtube.com/@c...",
				dueDate: "2025-10-03",
				completed: false,
				tags: ["Pessoal 😊"],
				projectId: "3",
				userId: MOCK_USER_ID,
			},
			{
				id: "8",
				title: "Diário - Uma carta para seu eu de amanhã",
				description: "Eu sou capaz de alcançar o s...",
				dueDate: "2025-12-10",
				completed: false,
				tags: ["Pessoal 😊", "Hábitos"],
				projectId: "3",
				userId: MOCK_USER_ID,
			},
			{
				id: "9",
				title: "🧠 Planning Mensal",
				description: "Rotina: Verificar quais as met...",
				dueDate: "2025-12-27",
				completed: false,
				tags: ["Pessoal 😊", "Rotinas 📆"],
				projectId: "3",
				userId: MOCK_USER_ID,
			},
			{
				id: "10",
				title: "Meditação",
				description: "3/310 vezes no ano",
				dueDate: "2024-12-16",
				completed: false,
				tags: ["Pessoal 😊", "Hábitos"],
				projectId: "3",
				userId: MOCK_USER_ID,
			},
			{
				id: "11",
				title: "Cripto",
				description: "Comprar Cripto de acordo co...",
				dueDate: "2025-06-30",
				completed: false,
				tags: ["Pessoal 😊", "Finanças"],
				projectId: "3",
				userId: MOCK_USER_ID,
			},
		],
	},
	{
		id: "4",
		name: "Profissional",
		emoji: "💼",
		userId: MOCK_USER_ID,
		todos: [
			{
				id: "12",
				title: "Separando testes de regra de negócios de testes de frameworks",
				description: "#3 Clean Architecture & Type...",
				dueDate: "2025-05-15",
				completed: false,
				tags: ["Profissional 💼", "NodeJS"],
				projectId: "4",
				userId: MOCK_USER_ID,
			},
			{
				id: "13",
				title: "High order function",
				description: "Higher Order Functions",
				dueDate: "2025-05-20",
				completed: false,
				tags: ["Profissional 💼", "NodeJS"],
				projectId: "4",
				userId: MOCK_USER_ID,
			},
			{
				id: "14",
				title: "Revisar tasks",
				dueDate: "2025-05-21",
				completed: false,
				tags: ["Profissional 💼"],
				projectId: "4",
				userId: MOCK_USER_ID,
			},
			{
				id: "15",
				title: "Read daily.dev",
				dueDate: "2025-12-04",
				completed: false,
				tags: ["Profissional 💼", "Conteúdos q..."],
				comments: 3,
				projectId: "4",
				userId: MOCK_USER_ID,
			},
			{
				id: "16",
				title: "Linkedin",
				description: "Acessar o linkedin todos os di...",
				dueDate: "2025-12-10",
				completed: false,
				tags: ["Profissional 💼"],
				comments: 3,
				projectId: "4",
				userId: MOCK_USER_ID,
			},
		],
	},
];
