# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vitorrsousaa
# "service" is the name of this project. This will also be added to your AWS resource names.
service: LifeOS
useDotenv: true

package:
  individually: true

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentMethod: direct
  architecture: arm64
  memorySize: 128
  environment:
    STAGE: ${self:provider.stage}
    COGNITO_CLIENT_ID: !Ref UserPoolClient
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience: !Ref UserPoolClient
    cors:
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cognito-idp:AdminGetUser"
          Resource: !GetAtt UserPool.Arn
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:ConditionCheckItem
            - dynamodb:BatchWriteItem
          Resource: 
            - !GetAtt DatabaseTable.Arn
            - !Sub ${DatabaseTable.Arn}/index/GSI1Index

custom:
  userPoolName: ${self:service}-${self:provider.stage}-UserPool
  userPoolDomain: lifeos-${self:provider.stage}-userpool
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
    target: node20
    
resources:
  - ${file(./serverless/resources/UserPool.yml)}
  - ${file(./serverless/resources/Database.yml)}

functions:
  signup:
    handler: src/server/functions/auth/signup/index.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
  signin:
    handler: src/server/functions/auth/signin/index.handler
    events:
      - httpApi:
          path: /auth/signin
          method: post
  profile:
    handler: src/server/functions/auth/profile/index.handler
    events:
      - httpApi:
          path: /auth/profile
          method: get
          authorizer: 
            name: CognitoAuthorizer
  preSignUpTrigger:
    handler: src/server/triggers/auth/presignup/index.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPoolName}
          trigger: PreSignUp
          existing: true
          forceDeploy: true
  getTodos:
    handler: src/server/functions/todo/get-todos/index.handler
    events:
      - httpApi:
          path: /todos
          method: get
          authorizer: 
            name: CognitoAuthorizer
  getInboxTodos:
    handler: src/server/functions/todo/get-inbox-todos/index.handler
    events:
      - httpApi:
          path: /todos/inbox
          method: get
          authorizer: 
            name: CognitoAuthorizer
  getTodayTasks:
    handler: src/server/functions/tasks/get-today-tasks/index.handler
    events:
      - httpApi:
          path: /tasks/today
          method: get
          authorizer: 
            name: CognitoAuthorizer
  getDashboardAnalytics:
    handler: src/server/functions/tasks/get-dashboard-analytics/index.handler
    events:
      - httpApi:
          path: /tasks/dashboard
          method: get
          authorizer: 
            name: CognitoAuthorizer
  getAllProjectsByUser:
    handler: src/server/functions/projects/get-all-projects-by-user/index.handler
    events:
      - httpApi:
          path: /projects
          method: get
          authorizer: 
            name: CognitoAuthorizer
  createProject:
    handler: src/server/functions/projects/create-project/index.handler
    events:
      - httpApi:
          path: /projects
          method: post
          authorizer: 
            name: CognitoAuthorizer
  getProjectDetail:
    handler: src/server/functions/projects/get-project-detail/index.handler
    events:
      - httpApi:
          path: /projects/{projectId}/detail
          method: get
          authorizer: 
            name: CognitoAuthorizer
  createSection:
    handler: src/server/functions/sections/create-section/index.handler
    events:
      - httpApi:
          path: /projects/{projectId}/sections
          method: post
          authorizer: 
            name: CognitoAuthorizer
  getAllByProject:
    handler: src/server/functions/sections/get-all-by-project/index.handler
    events:
      - httpApi:
          path: /projects/{projectId}/sections
          method: get
          authorizer: 
            name: CognitoAuthorizer
  createTodo:
    handler: src/server/functions/todo/create-todo/index.handler
    events:
      - httpApi:
          path: /todos
          method: post
          authorizer: 
            name: CognitoAuthorizer